// Generated by gencpp from file controle/ChangeModeResponse.msg
// DO NOT EDIT!


#ifndef CONTROLE_MESSAGE_CHANGEMODERESPONSE_H
#define CONTROLE_MESSAGE_CHANGEMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controle
{
template <class ContainerAllocator>
struct ChangeModeResponse_
{
  typedef ChangeModeResponse_<ContainerAllocator> Type;

  ChangeModeResponse_()
    : status(false)  {
    }
  ChangeModeResponse_(const ContainerAllocator& _alloc)
    : status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::controle::ChangeModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controle::ChangeModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeModeResponse_

typedef ::controle::ChangeModeResponse_<std::allocator<void> > ChangeModeResponse;

typedef boost::shared_ptr< ::controle::ChangeModeResponse > ChangeModeResponsePtr;
typedef boost::shared_ptr< ::controle::ChangeModeResponse const> ChangeModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controle::ChangeModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controle::ChangeModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controle::ChangeModeResponse_<ContainerAllocator1> & lhs, const ::controle::ChangeModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controle::ChangeModeResponse_<ContainerAllocator1> & lhs, const ::controle::ChangeModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controle::ChangeModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controle::ChangeModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controle::ChangeModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controle::ChangeModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controle::ChangeModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controle::ChangeModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controle::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a1255d4d998bd4d6585c64639b5ee9a";
  }

  static const char* value(const ::controle::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a1255d4d998bd4dULL;
  static const uint64_t static_value2 = 0x6585c64639b5ee9aULL;
};

template<class ContainerAllocator>
struct DataType< ::controle::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controle/ChangeModeResponse";
  }

  static const char* value(const ::controle::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controle::ChangeModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool status\n"
;
  }

  static const char* value(const ::controle::ChangeModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controle::ChangeModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controle::ChangeModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controle::ChangeModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLE_MESSAGE_CHANGEMODERESPONSE_H
