// Generated by gencpp from file controle/Distance.msg
// DO NOT EDIT!


#ifndef CONTROLE_MESSAGE_DISTANCE_H
#define CONTROLE_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace controle
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : desired(0.0)
    , observation(0.0)
    , current(0.0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : desired(0.0)
    , observation(0.0)
    , current(0.0)  {
  (void)_alloc;
    }



   typedef float _desired_type;
  _desired_type desired;

   typedef float _observation_type;
  _observation_type observation;

   typedef float _current_type;
  _current_type current;





  typedef boost::shared_ptr< ::controle::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::controle::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::controle::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::controle::Distance > DistancePtr;
typedef boost::shared_ptr< ::controle::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::controle::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::controle::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::controle::Distance_<ContainerAllocator1> & lhs, const ::controle::Distance_<ContainerAllocator2> & rhs)
{
  return lhs.desired == rhs.desired &&
    lhs.observation == rhs.observation &&
    lhs.current == rhs.current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::controle::Distance_<ContainerAllocator1> & lhs, const ::controle::Distance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace controle

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::controle::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::controle::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controle::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::controle::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controle::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::controle::Distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::controle::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4895d7c7873380c6167cc39276347c1e";
  }

  static const char* value(const ::controle::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4895d7c7873380c6ULL;
  static const uint64_t static_value2 = 0x167cc39276347c1eULL;
};

template<class ContainerAllocator>
struct DataType< ::controle::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "controle/Distance";
  }

  static const char* value(const ::controle::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::controle::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 desired\n"
"float32 observation\n"
"float32 current\n"
;
  }

  static const char* value(const ::controle::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::controle::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.desired);
      stream.next(m.observation);
      stream.next(m.current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::controle::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::controle::Distance_<ContainerAllocator>& v)
  {
    s << indent << "desired: ";
    Printer<float>::stream(s, indent + "  ", v.desired);
    s << indent << "observation: ";
    Printer<float>::stream(s, indent + "  ", v.observation);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROLE_MESSAGE_DISTANCE_H
