// Generated by gencpp from file state_machine/DesiredDistance.msg
// DO NOT EDIT!


#ifndef STATE_MACHINE_MESSAGE_DESIREDDISTANCE_H
#define STATE_MACHINE_MESSAGE_DESIREDDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace state_machine
{
template <class ContainerAllocator>
struct DesiredDistance_
{
  typedef DesiredDistance_<ContainerAllocator> Type;

  DesiredDistance_()
    : header()
    , desired_distance(0.0)  {
    }
  DesiredDistance_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , desired_distance(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _desired_distance_type;
  _desired_distance_type desired_distance;





  typedef boost::shared_ptr< ::state_machine::DesiredDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::state_machine::DesiredDistance_<ContainerAllocator> const> ConstPtr;

}; // struct DesiredDistance_

typedef ::state_machine::DesiredDistance_<std::allocator<void> > DesiredDistance;

typedef boost::shared_ptr< ::state_machine::DesiredDistance > DesiredDistancePtr;
typedef boost::shared_ptr< ::state_machine::DesiredDistance const> DesiredDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::state_machine::DesiredDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::state_machine::DesiredDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::state_machine::DesiredDistance_<ContainerAllocator1> & lhs, const ::state_machine::DesiredDistance_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.desired_distance == rhs.desired_distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::state_machine::DesiredDistance_<ContainerAllocator1> & lhs, const ::state_machine::DesiredDistance_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace state_machine

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::state_machine::DesiredDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::state_machine::DesiredDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::DesiredDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::state_machine::DesiredDistance_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::DesiredDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::state_machine::DesiredDistance_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::state_machine::DesiredDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5094fd976ee33ff6551fcacedcbae61f";
  }

  static const char* value(const ::state_machine::DesiredDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5094fd976ee33ff6ULL;
  static const uint64_t static_value2 = 0x551fcacedcbae61fULL;
};

template<class ContainerAllocator>
struct DataType< ::state_machine::DesiredDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "state_machine/DesiredDistance";
  }

  static const char* value(const ::state_machine::DesiredDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::state_machine::DesiredDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 desired_distance\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::state_machine::DesiredDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::state_machine::DesiredDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.desired_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DesiredDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::state_machine::DesiredDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::state_machine::DesiredDistance_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "desired_distance: ";
    Printer<double>::stream(s, indent + "  ", v.desired_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // STATE_MACHINE_MESSAGE_DESIREDDISTANCE_H
