// Generated by gencpp from file general_functions/Position.msg
// DO NOT EDIT!


#ifndef GENERAL_FUNCTIONS_MESSAGE_POSITION_H
#define GENERAL_FUNCTIONS_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace general_functions
{
template <class ContainerAllocator>
struct Position_
{
  typedef Position_<ContainerAllocator> Type;

  Position_()
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
    }
  Position_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef double _x_type;
  _x_type x;

   typedef double _y_type;
  _y_type y;

   typedef double _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::general_functions::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::general_functions::Position_<ContainerAllocator> const> ConstPtr;

}; // struct Position_

typedef ::general_functions::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::general_functions::Position > PositionPtr;
typedef boost::shared_ptr< ::general_functions::Position const> PositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::general_functions::Position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::general_functions::Position_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::general_functions::Position_<ContainerAllocator1> & lhs, const ::general_functions::Position_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::general_functions::Position_<ContainerAllocator1> & lhs, const ::general_functions::Position_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace general_functions

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::general_functions::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::general_functions::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_functions::Position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::general_functions::Position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_functions::Position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::general_functions::Position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::general_functions::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57832a67d2f8a00310788a06c92c59b2";
  }

  static const char* value(const ::general_functions::Position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57832a67d2f8a003ULL;
  static const uint64_t static_value2 = 0x10788a06c92c59b2ULL;
};

template<class ContainerAllocator>
struct DataType< ::general_functions::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "general_functions/Position";
  }

  static const char* value(const ::general_functions::Position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::general_functions::Position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 x\n"
"float64 y\n"
"float64 angle\n"
;
  }

  static const char* value(const ::general_functions::Position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::general_functions::Position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::general_functions::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::general_functions::Position_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GENERAL_FUNCTIONS_MESSAGE_POSITION_H
